# Generated by Django 3.0.5 on 2020-05-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20200511_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('delivery_address', models.CharField(max_length=200)),
                ('delivery_postcode', models.CharField(max_length=7)),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
