# Generated by Django 3.0.5 on 2020-05-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_price',
            name='ordered_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
