# Generated by Django 3.0.5 on 2020-05-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200511_1648'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Price',
            new_name='ProductPrice',
        ),
    ]
