# Generated by Django 3.0.5 on 2020-05-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0002_auto_20200517_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='products.Product'),
        ),
    ]
