# Generated by Django 3.0.5 on 2020-04-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('image_url', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('stock_quantity', models.IntegerField()),
            ],
        ),
    ]
