# Generated by Django 3.0.5 on 2020-04-28 10:29

import autoslug.fields
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('image_url', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('stock_quantity', models.IntegerField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=products.models.get_populate_from)),
            ],
        ),
    ]
